environments:
    - name: 本地
      url: ws://127.0.0.1:8089/
      enterprises:
        - name: 演示厂商
          short_name: demo
          device_types:
            - name: A3 音箱
              short_name: A3
    - name: 新加坡
      url: ws://aichatbotws-sgp.eye4.cn/{enterprise}
      http_url: https://aichatbotwx-sgp.eye4.cn/
      enterprises:
        - name: 欧堡
          short_name: GDOBZND
          device_types:
            - name: MH8W
              short_name: MH8W-GDOBZND-EN
    - name: 杭州
      url: ws://aichatbotws.eye4.cn/{enterprise}
      http_url: https://aichatbotwx.eye4.cn/
      enterprises:
        - name: 乐智创展
          short_name: STSCHQL
          device_types:
            - name: MH3W-STSCHQL
              short_name: MH3W-STSCHQL
    - name: 测试
      url: ws://aichatbotws.eye4.cn/veepai-test
      http_url: https://aichatbotwx.eye4.cn/veepai-test/
      enterprises:
        - name: 测试
          short_name: veepai-test
          device_types:
            - name: VOICE-TEST
              short_name: VOICE-TEST
