environments:
    - name: 本地
      url: ws://127.0.0.1:8089/
      enterprises:
        - name: 演示厂商
          short_name: demo
          device_types:
            - name: A3 音箱
              short_name: A3
    - name: 新加坡
      url: ws://aichatbotws-sgp.eye4.cn/{enterprise}
      enterprises:
        - name: 欧堡
          short_name: GDOBZND
          device_types:
            - name: MH8W
              short_name: MH8W-GDOBZND-EN
